language: java
script: cd ice-boar && mvn javadoc:jar source:jar deploy --settings settings.xml && cd .. && mvn clean install
jdk:
  - oraclejdk8
before_install:
  - pip install --user codecov
after_success:
  - codecov
cache:
  directories:
  - $HOME/.m2