language: java
script: 
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && cd ice-boar && mvn javadoc:jar source:jar deploy --settings settings.xml && cd .. && mvn clean install -U && cd ice-boar-samples/ice-boar-demo-gh-pages/ && mvn clean install -P ghpages && git clone https://github.com/Roche/IceBoar && cd IceBoar && git checkout gh-pages && cp -R ../target/ice-boar-demo-gh-pages/* . && git config user.name "Marcin Stachniuk" && git config user.email marcin.stachniuk@contractors.roche.com && git add -A && git commit -m "update gh-pages by Travis-CI" && git push ${GIT_HUB_REPO_SECRET}'
  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && cd ice-boar && mvn javadoc:jar source:jar install && cd .. && mvn clean install -U'
jdk:
  - oraclejdk8
before_install:
  - pip install --user codecov
after_success:
  - codecov
cache:
  directories:
  - $HOME/.m2
